/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AddressInfoApplyConfiguration represents an declarative configuration of the AddressInfo type for use
// with apply.
type AddressInfoApplyConfiguration struct {
	OSExtIPSMACMacAddr *string `json:"osExtIPSMACMacAddr,omitempty"`
	Address            *string `json:"addr,omitempty"`
	Version            *string `json:"version,omitempty"`
	OSExtIPSType       *string `json:"osExtIPSType,omitempty"`
}

// AddressInfoApplyConfiguration constructs an declarative configuration of the AddressInfo type for use with
// apply.
func AddressInfo() *AddressInfoApplyConfiguration {
	return &AddressInfoApplyConfiguration{}
}

// WithOSExtIPSMACMacAddr sets the OSExtIPSMACMacAddr field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OSExtIPSMACMacAddr field is set to the value of the last call.
func (b *AddressInfoApplyConfiguration) WithOSExtIPSMACMacAddr(value string) *AddressInfoApplyConfiguration {
	b.OSExtIPSMACMacAddr = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *AddressInfoApplyConfiguration) WithAddress(value string) *AddressInfoApplyConfiguration {
	b.Address = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AddressInfoApplyConfiguration) WithVersion(value string) *AddressInfoApplyConfiguration {
	b.Version = &value
	return b
}

// WithOSExtIPSType sets the OSExtIPSType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OSExtIPSType field is set to the value of the last call.
func (b *AddressInfoApplyConfiguration) WithOSExtIPSType(value string) *AddressInfoApplyConfiguration {
	b.OSExtIPSType = &value
	return b
}
